sudo: false
language: python

matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27
    - python: '3.3'
      env: TOXENV=py33
    - python: '3.4'
      env: TOXENV=py34
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: 'pypy'
      env: TOXENV=pypy
    - env: TOXENV=flake8
    - env: TOXENV=checkspelling

addons:
  apt:
    packages:
    - libtidy-0.99-0
    - aspell
    - aspell-en

install:
  - pip install tox
  - pip install 'coverage<4.0'
  - pip install codecov

script:
  - tox

after_success:
  - codecov

branches:
  only:
    - master
    - md3
